### ISSUE TITLE
Suggestion: Have You Considered Comparing Moxin-LLM with CT-LLM and MAP-Neo?

### ISSUE THREAD

**Issue by XinrunDu** [moxin-org/Moxin-LLM#3]
Dear Moxin-LLM Team,

I hope this message finds you well. Your contributions are highly valuable to the community, and I appreciate the effort you have put into this project.

I was wondering if you have considered comparing your model to other similar works such as MAP-Neo and CT-LLM. These models, like yours, contribute precious training resources to the open-source bilingual language model community. A comparison could provide interesting insights and further highlight the strengths of your model.

Thank you once again for your outstanding contributions. I look forward to seeing your future advancements in this area.

MAP-Neo: [MAP-Neo (map-neo.github.io)](https://map-neo.github.io/)
CT-LLM: [Chinese Tiny LLM (chinese-tiny-llm.github.io)](https://chinese-tiny-llm.github.io/)

Best regards,

M-A-P Team

**Comment by piuzha** [comment]
Many thanks for the suggestions. We will look into this.
